services:
  tap-tap-quizz:
    build: .
    container_name: TapTapQuizz
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./resources/images:/app/resources/images:ro