services:
  TapTapQuizz:
    build: .
    container_name: TapTapQuizz
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/data/Bots/TapTapQuizz/data:/app/data
      - /mnt/data/Bots/TapTapQuizz/resources/images:/app/resources/images:ro